server:
  port: 80
  servlet:
    session:
      timeout: 30s

spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/non_jpa_db?serverTimezone=UTC&useSSL=false
    url: jdbc:mysql://k9pkqwlvuzld2kx8:s1r2ci6sgxeyecz5@yjo6uubt3u5c16az.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/qz4x21t4qej1mn8w?serverTimezone=UTC&useSSL=false
    username: k9pkqwlvuzld2kx8
    password: s1r2ci6sgxeyecz5
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect

  jpa:
    properties:
      hibernate: default_batch_fetch_size =1000
    open-in-view: false
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
